name: Convert JSON to HTML (Python)

on:
  push:
    paths:
      - "data.json"      # Déclenché si data.json change
  workflow_dispatch:     # Déclenchement manuel possible

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Générer le HTML à partir du JSON
        run: python generate_html.py

      - name: Commit & push du HTML généré
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add output.html
          git commit -m "Mise à jour automatique du HTML"
          git push
        continue-on-error: true  # évite l'erreur si rien n'a changé
